---
kind: pipeline
type: kubernetes
name: vue-todo

steps:
  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - docker build -f docker/prod.dockerfile -t vue-todo .
      - docker tag vue-todo:latest vue-todo:$(cat version | tr -d '\n')

volumes:
  - name: dockersock
    host:
      path: /var/run
