version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
      args:
        - PORT=8000
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./:/app
      - /app/tmp
